apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
images:
- name: atlasmap-operator
  newName: docker.io/atlasmap/atlasmap-operator
  newTag: 0.5.0
