# permissions for end users to view atlasmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atlasmap-viewer-role
rules:
- apiGroups:
  - atlasmap.io
  resources:
  - atlasmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - atlasmap.io
  resources:
  - atlasmaps/status
  verbs:
  - get
