apiVersion: atlasmap.io/v1alpha1
kind: AtlasMap
metadata:
  name: example-atlasmap
spec:
  # The number of desired replicas
  replicas: 1

  # The version of the AtlasMap to use. The default is 'latest'.
  # The default image name and tag can be overridden by providing arguments to the AtlasMap operator container
  # E.g: --atlasmap-image-name=docker.io/custom-namespace/custom-image --atlasmap-image-version=1.2.3
  # Or through environment variables ATLASMAP_IMAGE_NAME & ATLASMAP_IMAGE_VERSION
  # version: latest

  # The host name to use for the OpenShift route or Kubernetes Ingress. If not specified, this is generated automatically
  # routeHostName: example-atlasmap.192.168.42.115.nip.io

  # The amount of CPU to request
  # requestCPU: 200m

  # The amount of memory to request
  # requestMemory: 256Mi

  # The amount of CPU to limit
  # limitCPU: 300m

  # The amount of memory to limit
  # limitMemory: 512Mi
