name: 'Build'

on:
  push:
    branches: [ master ]
    tags: [ '[0-9]+\.[0-9]+\.[0-9]+' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: ${{ github.repository == 'atlasmap/atlasmap-operator' }}
    runs-on: ubuntu-latest
    name: Build AtlasMap Operator
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: --timeout=5m

    - run: make build

    - run: make bundle

    - run: make test

    - run: echo "VERSION=latest" >> $GITHUB_ENV
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    - run: echo "VERSION=${GITHUB_REF#refs\/tags\/}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

    - name: Publish Docker Image
      if: ${{ github.event_name == 'push' && env.VERSION}}
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        make docker-build docker-push VERSION=${{ env.VERSION }}
        make bundle bundle-build bundle-push VERSION=${{ env.VERSION }}
        docker login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io
        make build docker-build docker-push REGISTRY="quay.io" VERSION=${{ env.VERSION }}
        make bundle bundle-build bundle-push REGISTRY="quay.io" VERSION=${{ env.VERSION }}
